### ISSUE TITLE
nuswide数据集上的表现有问题，损失在比较的的情况下，map却一直在0.36附近

### ISSUE THREAD

**Issue by Mahiro2211** [zzidlezz/SCCGDH#4]
![image](https://github.com/zzidlezz/SCCGDH/assets/130811701/ec70c0cc-17b4-4b59-a3ee-b0dea7f5c123)
考虑到没有提供对应的mat文件，我尝试自己接数据集，发现表现的不符合理想，是否也要resize为224的尺寸

**Comment by zzidlezz** [comment]
感谢你的关注，可以参考下https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A中两个nuswide数据集的划分，提取码tpmb，你也可以把你的数据集分享下，一起分析下原因

**Comment by Mahiro2211** [comment]
非常感谢，我也观察到了，数据集划分的方式并不是一样的。但是导致这样的结果可能是数据处理的问题。
这是我用的数据集
链接: https://pan.baidu.com/s/1_9TQbLcuc4TGPtHizOd1_w 提取码: ztcr 
--来自百度网盘超级会员v4的分享

**Comment by Mahiro2211** [comment]
但是我花了好几天也没想出结果。

**Comment by Maadaka** [comment]
> 感谢你的关注，可以参考下[https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A中两个nuswide数据集的划分，提取码tpmb，你也可以把你的数据集分享下，一起分析下原因](https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A%E4%B8%AD%E4%B8%A4%E4%B8%AAnuswide%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%92%E5%88%86%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81tpmb%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%8A%8A%E4%BD%A0%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%86%E4%BA%AB%E4%B8%8B%EF%BC%8C%E4%B8%80%E8%B5%B7%E5%88%86%E6%9E%90%E4%B8%8B%E5%8E%9F%E5%9B%A0)

您好，您附注的网盘链接密码不正确，请问是否方便提供新的密码

**Comment by Mahiro2211** [comment]
https://pan.baidu.com/s/1f9mKXE2T8XpIq8p7y8Fa6Q
password : uhr3
我使用的为这个数据集

**Comment by Mahiro2211** [comment]
> > 感谢你的关注，可以参考下[https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A中两个nuswide数据集的划分，提取码tpmb，你也可以把你的数据集分享下，一起分析下原因](https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A%E4%B8%AD%E4%B8%A4%E4%B8%AAnuswide%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%92%E5%88%86%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81tpmb%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%8A%8A%E4%BD%A0%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%86%E4%BA%AB%E4%B8%8B%EF%BC%8C%E4%B8%80%E8%B5%B7%E5%88%86%E6%9E%90%E4%B8%8B%E5%8E%9F%E5%9B%A0)
> 
> 您好，您附注的网盘链接密码不正确，请问是否方便提供新的密码
https://pan.baidu.com/s/1f9mKXE2T8XpIq8p7y8Fa6Q
password : uhr3
我使用的为这个数据集

**Comment by Lz-hh** [comment]
> 感谢你的关注，可以参考下[https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A中两个nuswide数据集的划分，提取码tpmb，你也可以把你的数据集分享下，一起分析下原因](https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A%E4%B8%AD%E4%B8%A4%E4%B8%AAnuswide%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%92%E5%88%86%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81tpmb%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%8A%8A%E4%BD%A0%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%86%E4%BA%AB%E4%B8%8B%EF%BC%8C%E4%B8%80%E8%B5%B7%E5%88%86%E6%9E%90%E4%B8%8B%E5%8E%9F%E5%9B%A0)

您的文件过期了，可以在分享一下吗，谢谢您！

**Comment by Mahiro2211** [comment]
您好
https://pan.baidu.com/s/1f9mKXE2T8XpIq8p7y8Fa6Q
password : uhr3
我使用的为这个数据集

**Comment by Mahiro2211** [comment]
> > 感谢你的关注，可以参考下[https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A中两个nuswide数据集的划分，提取码tpmb，你也可以把你的数据集分享下，一起分析下原因](https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A%E4%B8%AD%E4%B8%A4%E4%B8%AAnuswide%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%92%E5%88%86%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81tpmb%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%8A%8A%E4%BD%A0%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%86%E4%BA%AB%E4%B8%8B%EF%BC%8C%E4%B8%80%E8%B5%B7%E5%88%86%E6%9E%90%E4%B8%8B%E5%8E%9F%E5%9B%A0)
> 
> 您的文件过期了，可以在分享一下吗，谢谢您！
您好
https://pan.baidu.com/s/1f9mKXE2T8XpIq8p7y8Fa6Q
password : uhr3
我使用的为这个数据集

**Comment by Lz-hh** [comment]
谢谢！请问您有[SCCGDH]这个工作的nuswide的数据集划分方式吗？或者相应的mat文件？

**Comment by Lz-hh** [comment]
> > > 感谢你的关注，可以参考下[https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A中两个nuswide数据集的划分，提取码tpmb，你也可以把你的数据集分享下，一起分析下原因](https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A%E4%B8%AD%E4%B8%A4%E4%B8%AAnuswide%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%92%E5%88%86%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81tpmb%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%8A%8A%E4%BD%A0%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%86%E4%BA%AB%E4%B8%8B%EF%BC%8C%E4%B8%80%E8%B5%B7%E5%88%86%E6%9E%90%E4%B8%8B%E5%8E%9F%E5%9B%A0)
> > 
> > 
> > 您的文件过期了，可以在分享一下吗，谢谢您！
> > 您好
> > https://pan.baidu.com/s/1f9mKXE2T8XpIq8p7y8Fa6Q
> > password : uhr3
> > 我使用的为这个数据集

谢谢！请问您有[SCCGDH]这个工作的nuswide的数据集划分方式吗？或者相应的mat文件？

**Comment by Mahiro2211** [comment]
> > > > 感谢你的关注，可以参考下[https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A中两个nuswide数据集的划分，提取码tpmb，你也可以把你的数据集分享下，一起分析下原因](https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A%E4%B8%AD%E4%B8%A4%E4%B8%AAnuswide%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%92%E5%88%86%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81tpmb%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%8A%8A%E4%BD%A0%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%86%E4%BA%AB%E4%B8%8B%EF%BC%8C%E4%B8%80%E8%B5%B7%E5%88%86%E6%9E%90%E4%B8%8B%E5%8E%9F%E5%9B%A0)
> > > 
> > > 
> > > 您的文件过期了，可以在分享一下吗，谢谢您！
> > > 您好
> > > https://pan.baidu.com/s/1f9mKXE2T8XpIq8p7y8Fa6Q
> > > password : uhr3
> > > 我使用的为这个数据集
> 
> 谢谢！请问您有[SCCGDH]这个工作的nuswide的数据集划分方式吗？或者相应的mat文件？
您好，目前我想的是把这个跨模态的任务迁移到单模态的图像检索任务中，私以为不能用这篇论文的划分数据集的方式
有关这篇论文的数据集划分的mat文件你可以去这里。https://github.com/BMC-SDNU/Cross-Modal-Hashing-Retrieval
这个链接就是这篇论文的数据集

**Comment by Mahiro2211** [comment]
> > > > 感谢你的关注，可以参考下[https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A中两个nuswide数据集的划分，提取码tpmb，你也可以把你的数据集分享下，一起分析下原因](https://pan.baidu.com/s/1xFRRMSlK7Z2jK1C7aHZD1A%E4%B8%AD%E4%B8%A4%E4%B8%AAnuswide%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%92%E5%88%86%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81tpmb%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%8A%8A%E4%BD%A0%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%86%E4%BA%AB%E4%B8%8B%EF%BC%8C%E4%B8%80%E8%B5%B7%E5%88%86%E6%9E%90%E4%B8%8B%E5%8E%9F%E5%9B%A0)
> > > 
> > > 
> > > 您的文件过期了，可以在分享一下吗，谢谢您！
> > > 您好
> > > https://pan.baidu.com/s/1f9mKXE2T8XpIq8p7y8Fa6Q
> > > password : uhr3
> > > 我使用的为这个数据集
> 
> 谢谢！请问您有[SCCGDH]这个工作的nuswide的数据集划分方式吗？或者相应的mat文件？





您好，目前我想的是把这个跨模态的任务迁移到单模态的图像检索任务中，私以为不能用这篇论文的划分数据集的方式
有关这篇论文的数据集划分的mat文件你可以去这里。https://github.com/BMC-SDNU/Cross-Modal-Hashing-Retrieval
这个链接就是这篇论文的数据集

**Comment by Mahiro2211** [comment]
我发现了问题所在，原论文中计算了mAP@50而我计算了5000，这个可能是原因，因为原论文的模型参数确实非常精简非常小，但是这篇论文的创新点非常好，我认为后续迁移到参数大的模型会有更好的表现。。。
